# Generated by Django 5.2.8 on 2025-11-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalas', '0002_remove_product_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
